feat(web3): get peers from registry
airswap/airswap-indexer-node pull request #18
Opened 2022-07-27 19:00 UTC by Mitsichury

2022-08-02 18:18 UTC, Mitsichury commented on .env.example
> +ABI='[{"inputs":[{"internalType":"contract IERC20","name":"_stakingToken","type":"address"},{"internalType":"uint256","name":"_obligationCost","type":"uint256"}],"stateMutability":"nonpayable","type"
current goerli indexer registry is 0xC32a3c867aBAd28d977e1724f92D9684fF3d2976
you can also grab latest indexer registry addresses from @airswap/indexers/deploys.js

2022-08-09 13:52 UTC, dmosites requested changes
Looks sane to me. Think we should remove the existing registry server and client to remove any confusion about server discovery.

2022-08-09 13:52 UTC, dmosites commented on README.md
> +Then in anoter one:
"another"

2022-08-09 13:52 UTC, dmosites commented on src/client/__tests__/Web3RegistryClient.test.ts
> +    const registryAddress = "registryAddres";
"registryAddress"

2022-08-09 18:06 UTC, Mitsichury commented on README.md
> +Then in anoter one:
thx :)

2022-08-09 18:08 UTC, dmosites approved these changes

2022-08-10 16:00 UTC, merged